-- 用户登录表 (users)
-- 适用于 Supabase (PostgreSQL)

CREATE TABLE IF NOT EXISTS users (
    -- 主键 ID，使用 BIGINT 自增，保持与现有 Python 代码 id: int 的兼容性
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 登录凭证
    username TEXT UNIQUE,              -- 用户名 (可选)
    email TEXT UNIQUE,                 -- 邮箱 (可选)
    password_hash TEXT,                -- 密码哈希 (存储加密后的密码)
    
    -- 第三方登录
    wechat_openid TEXT UNIQUE,         -- 微信 OpenID (用于关联微信小程序用户)
    
    -- 用户基本信息
    nickname TEXT DEFAULT '用户',      -- 昵称
    avatar_url TEXT,                   -- 头像链接
    role TEXT DEFAULT 'user',          -- 角色: user, admin
    
    -- 状态与时间
    status TEXT DEFAULT 'active',      -- 状态: active, suspended
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引以加快查询速度
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_wechat_openid ON users(wechat_openid);

-- 添加更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- 注释
COMMENT ON TABLE users IS '用户登录及个人信息表';
COMMENT ON COLUMN users.id IS '用户ID';
COMMENT ON COLUMN users.username IS '用户名';
COMMENT ON COLUMN users.password_hash IS '加密后的密码';
COMMENT ON COLUMN users.wechat_openid IS '微信OpenID';
